# Generated by Django 5.1.14 on 2026-03-30 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0079_remove_botevent_valid_event_type_event_sub_type_combinations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotRuntimeLease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("digitalocean_droplet", "DigitalOcean Droplet")], max_length=64)),
                ("status", models.CharField(choices=[("provisioning", "Provisioning"), ("active", "Active"), ("delete_requested", "Delete Requested"), ("deleted", "Deleted"), ("failed", "Failed")], default="provisioning", max_length=32)),
                ("provider_instance_id", models.CharField(blank=True, max_length=64, null=True)),
                ("provider_name", models.CharField(blank=True, max_length=255, null=True)),
                ("region", models.CharField(blank=True, max_length=64, null=True)),
                ("size_class", models.CharField(blank=True, max_length=64, null=True)),
                ("snapshot_id", models.CharField(blank=True, max_length=64, null=True)),
                ("shutdown_token", models.CharField(editable=False, max_length=64, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_at", models.DateTimeField(blank=True, null=True)),
                ("delete_requested_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("bot", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="runtime_lease", to="bots.bot")),
            ],
        ),
    ]
