# Generated by Django 5.1.14 on 2026-03-31 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0080_botruntimelease"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botruntimelease",
            name="provider",
            field=models.CharField(choices=[("digitalocean_droplet", "DigitalOcean Droplet"), ("gcp_compute_instance", "GCP Compute Instance")], max_length=64),
        ),
        migrations.CreateModel(
            name="RuntimeCapacitySnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("gcp_compute_instance", "GCP Compute Instance")], max_length=64)),
                ("region", models.CharField(max_length=64)),
                ("quota_limit", models.IntegerField(default=0)),
                ("quota_usage", models.IntegerField(default=0)),
                ("soft_cap", models.IntegerField(blank=True, null=True)),
                ("effective_available", models.IntegerField(default=0)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={},
        ),
        migrations.AddConstraint(
            model_name="runtimecapacitysnapshot",
            constraint=models.UniqueConstraint(fields=("provider", "region"), name="unique_runtime_capacity_snapshot_provider_region"),
        ),
    ]
