# Generated by Django 5.1.14 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0081_runtimecapacitysnapshot_and_gcp_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botruntimelease",
            name="snapshot_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
