# Generated by Django 5.1.14 on 2026-04-11 07:43

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0083_backfill_recording_complete_upstream_signing_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botruntimelease',
            name='provider',
            field=models.CharField(choices=[('gcp_compute_instance', 'GCP Compute Instance'), ('vps_docker', 'VPS Docker')], max_length=64),
        ),
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FileField(max_length=500, storage=storages.backends.s3.S3Storage(access_key='b9f653d6445b99e9fe130595496a550a', bucket_name='vox-video', endpoint_url='https://830eacc6f0bf33e7119b6c71ed13e03d.eu.r2.cloudflarestorage.com', secret_key='8363ca72d753600fd62ed2b393c83c73a885acd1dc737fd5a714996ecaa060c9'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='runtimecapacitysnapshot',
            name='provider',
            field=models.CharField(choices=[('gcp_compute_instance', 'GCP Compute Instance'), ('vps_docker', 'VPS Docker')], max_length=64),
        ),
    ]
