# Generated by Codex on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0085_alter_zoomoauthconnection_is_onbehalf_token_supported"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="key_hash",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
