# Generated by Django 5.1.14 on 2026-07-15 07:23

import hashlib
import django.db.models.deletion
from django.db import migrations, models


def backfill_workspace_sso_tenants(apps, schema_editor):
    """Preserve legacy signing material but keep every migrated tenant disabled.

    Legacy logins stored their certificate/private key on each account.  The
    encrypted payload is safe to copy verbatim because it uses the same
    application-level Fernet key.  A human still has to configure the Google
    SP details and explicitly enable the new tenant before it can issue SAML.
    """

    GoogleMeetBotLogin = apps.get_model("bots", "GoogleMeetBotLogin")
    GoogleWorkspaceSsoTenant = apps.get_model("bots", "GoogleWorkspaceSsoTenant")
    GoogleWorkspaceSsoSigningCertificate = apps.get_model("bots", "GoogleWorkspaceSsoSigningCertificate")

    for login in GoogleMeetBotLogin.objects.select_related("group").order_by("id"):
        domain = (login.workspace_domain or "").strip().lower().rstrip(".")
        if not domain:
            continue
        project_id = login.group.project_id
        digest = hashlib.sha256(f"{project_id}:{domain}".encode()).hexdigest()[:16]
        tenant, created = GoogleWorkspaceSsoTenant.objects.get_or_create(
            project_id=project_id,
            workspace_domain=domain,
            defaults={
                "object_id": f"gst_mig_{digest}",
                "is_active": False,
            },
        )
        if not created or not login._encrypted_data:
            continue
        GoogleWorkspaceSsoSigningCertificate.objects.create(
            tenant=tenant,
            object_id=f"gsc_mig_{digest}",
            _encrypted_data=login._encrypted_data,
            state="active",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0086_alter_apikey_key_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleWorkspaceSsoTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('workspace_domain', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('idp_entity_id', models.CharField(blank=True, max_length=512)),
                ('google_sp_entity_id', models.CharField(blank=True, max_length=512)),
                ('google_acs_url', models.URLField(blank=True, max_length=1024)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_workspace_sso_tenants', to='bots.project')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleWorkspaceSsoSigningCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('_encrypted_data', models.BinaryField(null=True)),
                ('fingerprint_sha256', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(choices=[('active', 'Active'), ('next', 'Next'), ('retired', 'Retired')], default='active', max_length=16)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_certificates', to='bots.googleworkspacessotenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='googleworkspacessotenant',
            constraint=models.UniqueConstraint(fields=('project', 'workspace_domain'), name='unique_google_workspace_sso_tenant_domain'),
        ),
        migrations.RunPython(backfill_workspace_sso_tenants, migrations.RunPython.noop),
    ]
