services:
  attendee-worker-local:
    platform: linux/amd64
    build: ./
    env_file:
      - .env
    volumes:
      - .:/attendee
    networks:
      - attendee_network
    environment:
      DJANGO_SETTINGS_MODULE: attendee.settings.development
      ENABLE_CHROME_SANDBOX: "false"
    command: "celery -A attendee worker -l INFO"

  attendee-scheduler-local:
    platform: linux/amd64
    build: ./
    env_file:
      - .env
    volumes:
      - .:/attendee
    networks:
      - attendee_network
    environment:
      DJANGO_SETTINGS_MODULE: attendee.settings.development
    command: "uv run python manage.py run_scheduler"

  attendee-app-local:
    platform: linux/amd64
    build: ./
    env_file:
      - .env
    volumes:
      - .:/attendee
    networks:
      - attendee_network
    ports:
      - "8100:8100" 
    environment:
      DJANGO_SETTINGS_MODULE: attendee.settings.development
    command: >-
      sh -c "uv run python manage.py migrate --noinput &&
      uv run python manage.py runserver 0.0.0.0:8100"

  attendee-webpage-streamer-local:
    platform: linux/amd64
    build: ./
    env_file:
      - .env
    volumes:
      - .:/attendee
    networks:
      - attendee_network
    ports:
      - "8001:8100"
    environment:
      DJANGO_SETTINGS_MODULE: attendee.settings.development
      ENABLE_CHROME_SANDBOX: "true"
    command: "uv run python bots/webpage_streamer/run_webpage_streamer.py"
    security_opt:
      - seccomp=./bots/web_bot_adapter/chrome_seccomp.json
    profiles:
      - webpage-streamer

networks:
  attendee_network:
    driver: bridge
