from django.urls import path

from . import internal_views

app_name = "bots_internal"

urlpatterns = [
    path(
        "bot-runtime-leases/<int:lease_id>/complete",
        internal_views.BotRuntimeLeaseCompletionView.as_view(),
        name="bot-runtime-lease-complete",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/recording-complete",
        internal_views.BotRuntimeLeaseRecordingCompleteView.as_view(),
        name="bot-runtime-lease-recording-complete",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/bootstrap",
        internal_views.BotRuntimeLeaseBootstrapView.as_view(),
        name="bot-runtime-lease-bootstrap",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/control",
        internal_views.BotRuntimeLeaseControlView.as_view(),
        name="bot-runtime-lease-control",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/source-archive",
        internal_views.BotRuntimeLeaseSourceArchiveView.as_view(),
        name="bot-runtime-lease-source-archive",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/recordings/<int:recording_id>/file",
        internal_views.BotRuntimeLeaseRecordingFileView.as_view(),
        name="bot-runtime-lease-recording-file",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/bot-events",
        internal_views.BotRuntimeLeaseBotEventsView.as_view(),
        name="bot-runtime-lease-bot-events",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/participants/events",
        internal_views.BotRuntimeLeaseParticipantEventsView.as_view(),
        name="bot-runtime-lease-participant-events",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/chat-messages",
        internal_views.BotRuntimeLeaseChatMessagesView.as_view(),
        name="bot-runtime-lease-chat-messages",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/captions",
        internal_views.BotRuntimeLeaseCaptionsView.as_view(),
        name="bot-runtime-lease-captions",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/audio-chunks",
        internal_views.BotRuntimeLeaseAudioChunksView.as_view(),
        name="bot-runtime-lease-audio-chunks",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/bot-logs",
        internal_views.BotRuntimeLeaseBotLogsView.as_view(),
        name="bot-runtime-lease-bot-logs",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/resource-snapshots",
        internal_views.BotRuntimeLeaseResourceSnapshotsView.as_view(),
        name="bot-runtime-lease-resource-snapshots",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/heartbeat",
        internal_views.BotRuntimeLeaseHeartbeatView.as_view(),
        name="bot-runtime-lease-heartbeat",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/media-requests/<int:request_id>/status",
        internal_views.BotRuntimeLeaseMediaRequestStatusView.as_view(),
        name="bot-runtime-lease-media-request-status",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/chat-message-requests/<int:request_id>/status",
        internal_views.BotRuntimeLeaseChatMessageRequestStatusView.as_view(),
        name="bot-runtime-lease-chat-message-request-status",
    ),
    path(
        "bot-runtime-leases/<int:lease_id>/media-blobs/<str:object_id>",
        internal_views.BotRuntimeLeaseMediaBlobView.as_view(),
        name="bot-runtime-lease-media-blob",
    ),
]
