# stunnel server-side configuration for wrapping PostgreSQL
foreground = yes
debug = info

[postgresql]
accept = 5432
connect = postgres:5432
protocol = pgsql
cert = /etc/stunnel/stunnel.pem
key = /etc/stunnel/stunnel.key
